### ISSUE TITLE
Initial steps for Laddr extended site

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/codeforcroatia.org#48]
Steps:
- [x] 1. copy and customize this file into your codeforcroatia.org repo at the same path: https://github.com/SlateFoundation/scienceleadership-skeleton/blob/master/.github/workflows/holo.yml
- [x] 2. delete the Update holobranch: emergence/skeleton/master step, you don't need to publish a skeleton because your layer is a "leaf" node in the network --> see #49

Next steps - informational:
- [x] 3. once your emergence/vfs-site/master projection is published, ask Chris to execute this procedure on staging site: https://gist.github.com/themightychris/d7ac5906d8848128d6006a473a634b34
- [x] 4. from then on, your staging site will have a flat filesystem with codeforcroatia merged into laddr and its parents, and all builds already built, so it won't be a convenient place for live online editing of just the cfc bits anymore
- [x] 5. you can still hack on the live site, and we could even set up a 3 site chain staging->preprod->live that would give you back that space, or you could have two sibling sites `live` and `sandbox` both extending your staging site --> see #39 
- [x] 6. then on merge to master in your codeforcroatia repo, your staging site will get updated automatically by github like this: https://github.com/SlateFoundation/scienceleadership-skeleton/runs/411606895?check_suite_focus=true --> see #35
- [x] 7. and you could also then start managing what tag/branch of laddr you use like this: https://github.com/b21network/b21-skeleton/commit/feff18f2748de44b6d9b3bbf4f1706a628139f9d (see also https://github.com/SlateFoundation/slate-cbl/releases/tag/v3.0.0-beta.32)

**Comment by schlos** [comment]
See also https://github.com/codeforcroatia/codeforcroatia.org/issues/38 for next steps

**Comment by schlos** [comment]
First 2 steps are done. I've asked Chris to execute this procedure on staging site: https://gist.github.com/themightychris/d7ac5906d8848128d6006a473a634b34 (step 3).

Staging-v3 site is at  http://cfc-staging-v3.poplar.phl.io.

**Comment by schlos** [comment]
Step 6 looks OK: https://github.com/codeforcroatia/codeforcroatia.org/runs/1400347247?check_suite_focus=true except that it needs setup by Chris so that action is authorized on cfc-staging-v3.

![Screenshot 2020-11-14 at 17 57 01](https://user-images.githubusercontent.com/1014134/99152563-d250cc00-26a2-11eb-8e2e-cab3d399bd3a.png)

--> for Github Actions, we need to setup #35
